name: Jared Dillard
description: Jared Dillard, Web Developer from Austin, Texas
meta_description: "Jared Dillard, Web Developer from Austin, Texas"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: 'https://jareddillard.com'
url: 'https://jareddillard.com'
author: 'Jared Dillard'
title: "Jared Dillard"
google_analytics: 'UA-7883601-2 '
repository: jdillard/jdillard.github.io

include: ["_headers"]
exclude: ["Gemfile.lock","Rakefile","Gemfile","README.md","node_modules","npm-debug.log","package.json","vendor"]

twitter:
  username: itslogicwon
social:
  name: Jared Dillard
  links:
    - https://twitter.com/itslogicwon
    - https://www.linkedin.com/in/jareddillard
    - https://github.com/jdillard
    - https://www.instagram.com/farmerofbits/

permalink: /blog/:title.html

sass:
    style: compressed
