name: Trigger Netlify Build
on:
  schedule:
    # Run at 02:15 daily
    - cron: '15 2 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_DEPLOY_KEY }}
