name: Trigger Netlify Build
on:
  schedule:
    # Run at 02:15 daily
    # - cron: '15 8 * * *'
    - cron: '*/15 * * * '
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        env:
          NETLIFY_DEPLOY_KEY: ${{ secrets.NETLIFY_DEPLOY_KEY }}
        run: curl -X POST -d '{"scripts": "crags"}' https://api.netlify.com/build_hooks/$NETLIFY_DEPLOY_KEY
